[2024-11-16T11:12:37.206+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-16T11:12:31.532376+00:00/task_id=invoke_lambda_function permission to 509
[2024-11-16T11:12:37.206+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-16T11:12:31.532376+00:00/task_id=invoke_lambda_function permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-16T11:12:31.532376+00:00/task_id=invoke_lambda_function'
[2024-11-16T11:12:37.244+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-16T11:12:31.532376+00:00/task_id=invoke_lambda_function permission to 509
[2024-11-16T11:12:37.245+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-16T11:12:31.532376+00:00/task_id=invoke_lambda_function permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-16T11:12:31.532376+00:00/task_id=invoke_lambda_function'
[2024-11-16T11:12:37.276+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_training_pipeline.invoke_lambda_function manual__2024-11-16T11:12:31.532376+00:00 [queued]>
[2024-11-16T11:12:37.285+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_training_pipeline.invoke_lambda_function manual__2024-11-16T11:12:31.532376+00:00 [queued]>
[2024-11-16T11:12:37.285+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-11-16T11:12:37.299+0000] {taskinstance.py:1382} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_function> on 2024-11-16 11:12:31.532376+00:00
[2024-11-16T11:12:37.309+0000] {standard_task_runner.py:57} INFO - Started process 79086 to run task
[2024-11-16T11:12:37.311+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'model_training_pipeline', 'invoke_lambda_function', 'manual__2024-11-16T11:12:31.532376+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/model_training_pipeline_dag/model_training_dag.py', '--cfg-path', '/tmp/tmpbkxzmvwp']
[2024-11-16T11:12:37.314+0000] {standard_task_runner.py:85} INFO - Job 242: Subtask invoke_lambda_function
[2024-11-16T11:12:37.366+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-16T11:12:31.532376+00:00/task_id=invoke_lambda_function permission to 509
[2024-11-16T11:12:37.367+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-16T11:12:31.532376+00:00/task_id=invoke_lambda_function permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-16T11:12:31.532376+00:00/task_id=invoke_lambda_function'
[2024-11-16T11:12:37.369+0000] {task_command.py:415} INFO - Running <TaskInstance: model_training_pipeline.invoke_lambda_function manual__2024-11-16T11:12:31.532376+00:00 [running]> on host 16801ac1f6e4
[2024-11-16T11:12:37.463+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_training_pipeline' AIRFLOW_CTX_TASK_ID='invoke_lambda_function' AIRFLOW_CTX_EXECUTION_DATE='2024-11-16T11:12:31.532376+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-16T11:12:31.532376+00:00'
[2024-11-16T11:12:37.465+0000] {lambda_function.py:177} INFO - Invoking AWS Lambda function: natural_gas_spot_prices_transformation_trigger with payload: None
[2024-11-16T11:12:37.479+0000] {base.py:73} INFO - Using connection ID 'aws_connection' for task execution.
[2024-11-16T11:12:37.480+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_connection', conn_type='aws') credentials retrieved from login and password.
[2024-11-16T11:12:38.963+0000] {lambda_function.py:186} INFO - Lambda response metadata: {'RequestId': '3c7a0a6a-bc8a-41e2-b972-2bd4c5fa4fe1', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Sat, 16 Nov 2024 11:12:38 GMT', 'content-type': 'application/json', 'content-length': '232', 'connection': 'keep-alive', 'x-amzn-requestid': '3c7a0a6a-bc8a-41e2-b972-2bd4c5fa4fe1', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amz-log-result': 'U1RBUlQgUmVxdWVzdElkOiAzYzdhMGE2YS1iYzhhLTQxZTItYjk3Mi0yYmQ0YzVmYTRmZTEgVmVyc2lvbjogJExBVEVTVApMQU1CREFfV0FSTklORzogVW5oYW5kbGVkIGV4Y2VwdGlvbi4gVGhlIG1vc3QgbGlrZWx5IGNhdXNlIGlzIGFuIGlzc3VlIGluIHRoZSBmdW5jdGlvbiBjb2RlLiBIb3dldmVyLCBpbiByYXJlIGNhc2VzLCBhIExhbWJkYSBydW50aW1lIHVwZGF0ZSBjYW4gY2F1c2UgdW5leHBlY3RlZCBmdW5jdGlvbiBiZWhhdmlvci4gRm9yIGZ1bmN0aW9ucyB1c2luZyBtYW5hZ2VkIHJ1bnRpbWVzLCBydW50aW1lIHVwZGF0ZXMgY2FuIGJlIHRyaWdnZXJlZCBieSBhIGZ1bmN0aW9uIGNoYW5nZSwgb3IgY2FuIGJlIGFwcGxpZWQgYXV0b21hdGljYWxseS4gVG8gZGV0ZXJtaW5lIGlmIHRoZSBydW50aW1lIGhhcyBiZWVuIHVwZGF0ZWQsIGNoZWNrIHRoZSBydW50aW1lIHZlcnNpb24gaW4gdGhlIElOSVRfU1RBUlQgbG9nIGVudHJ5LiBJZiB0aGlzIGVycm9yIGNvcnJlbGF0ZXMgd2l0aCBhIGNoYW5nZSBpbiB0aGUgcnVudGltZSB2ZXJzaW9uLCB5b3UgbWF5IGJlIGFibGUgdG8gbWl0aWdhdGUgdGhpcyBlcnJvciBieSB0ZW1wb3JhcmlseSByb2xsaW5nIGJhY2sgdG8gdGhlIHByZXZpb3VzIHJ1bnRpbWUgdmVyc2lvbi4gRm9yIG1vcmUgaW5mb3JtYXRpb24sIHNlZSBodHRwczovL2RvY3MuYXdzLmFtYXpvbi5jb20vbGFtYmRhL2xhdGVzdC9kZy9ydW50aW1lcy11cGRhdGUuaHRtbA1bRVJST1JdIEtleUVycm9yOiAnUmVjb3JkcycKVHJhY2ViYWNrIChtb3N0IHJlY2VudCBjYWxsIGxhc3QpOgrCoMKgRmlsZSAiL3Zhci90YXNrL2xhbWJkYV9mdW5jdGlvbi5weSIsIGxpbmUgNywgaW4gbGFtYmRhX2hhbmRsZXIKwqDCoMKgwqBmb3IgcmVjb3JkIGluIGV2ZW50WydSZWNvcmRzJ106RU5EIFJlcXVlc3RJZDogM2M3YTBhNmEtYmM4YS00MWUyLWI5NzItMmJkNGM1ZmE0ZmUxClJFUE9SVCBSZXF1ZXN0SWQ6IDNjN2EwYTZhLWJjOGEtNDFlMi1iOTcyLTJiZDRjNWZhNGZlMQlEdXJhdGlvbjogNC4xMyBtcwlCaWxsZWQgRHVyYXRpb246IDUgbXMJTWVtb3J5IFNpemU6IDEyOCBNQglNYXggTWVtb3J5IFVzZWQ6IDMxIE1CCUluaXQgRHVyYXRpb246IDc0LjUwIG1zCQo=', 'x-amzn-trace-id': 'Root=1-67387e26-69be6870135a1afe3433f53e;Parent=75fc686d750fd7fc;Sampled=0;Lineage=1:1efcaaf0:0'}, 'RetryAttempts': 0}
[2024-11-16T11:12:38.964+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/operators/lambda_function.py", line 192, in execute
    raise ValueError(
ValueError: ('Lambda function execution resulted in error', {'ResponseMetadata': {'RequestId': '3c7a0a6a-bc8a-41e2-b972-2bd4c5fa4fe1', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Sat, 16 Nov 2024 11:12:38 GMT', 'content-type': 'application/json', 'content-length': '232', 'connection': 'keep-alive', 'x-amzn-requestid': '3c7a0a6a-bc8a-41e2-b972-2bd4c5fa4fe1', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amz-log-result': 'U1RBUlQgUmVxdWVzdElkOiAzYzdhMGE2YS1iYzhhLTQxZTItYjk3Mi0yYmQ0YzVmYTRmZTEgVmVyc2lvbjogJExBVEVTVApMQU1CREFfV0FSTklORzogVW5oYW5kbGVkIGV4Y2VwdGlvbi4gVGhlIG1vc3QgbGlrZWx5IGNhdXNlIGlzIGFuIGlzc3VlIGluIHRoZSBmdW5jdGlvbiBjb2RlLiBIb3dldmVyLCBpbiByYXJlIGNhc2VzLCBhIExhbWJkYSBydW50aW1lIHVwZGF0ZSBjYW4gY2F1c2UgdW5leHBlY3RlZCBmdW5jdGlvbiBiZWhhdmlvci4gRm9yIGZ1bmN0aW9ucyB1c2luZyBtYW5hZ2VkIHJ1bnRpbWVzLCBydW50aW1lIHVwZGF0ZXMgY2FuIGJlIHRyaWdnZXJlZCBieSBhIGZ1bmN0aW9uIGNoYW5nZSwgb3IgY2FuIGJlIGFwcGxpZWQgYXV0b21hdGljYWxseS4gVG8gZGV0ZXJtaW5lIGlmIHRoZSBydW50aW1lIGhhcyBiZWVuIHVwZGF0ZWQsIGNoZWNrIHRoZSBydW50aW1lIHZlcnNpb24gaW4gdGhlIElOSVRfU1RBUlQgbG9nIGVudHJ5LiBJZiB0aGlzIGVycm9yIGNvcnJlbGF0ZXMgd2l0aCBhIGNoYW5nZSBpbiB0aGUgcnVudGltZSB2ZXJzaW9uLCB5b3UgbWF5IGJlIGFibGUgdG8gbWl0aWdhdGUgdGhpcyBlcnJvciBieSB0ZW1wb3JhcmlseSByb2xsaW5nIGJhY2sgdG8gdGhlIHByZXZpb3VzIHJ1bnRpbWUgdmVyc2lvbi4gRm9yIG1vcmUgaW5mb3JtYXRpb24sIHNlZSBodHRwczovL2RvY3MuYXdzLmFtYXpvbi5jb20vbGFtYmRhL2xhdGVzdC9kZy9ydW50aW1lcy11cGRhdGUuaHRtbA1bRVJST1JdIEtleUVycm9yOiAnUmVjb3JkcycKVHJhY2ViYWNrIChtb3N0IHJlY2VudCBjYWxsIGxhc3QpOgrCoMKgRmlsZSAiL3Zhci90YXNrL2xhbWJkYV9mdW5jdGlvbi5weSIsIGxpbmUgNywgaW4gbGFtYmRhX2hhbmRsZXIKwqDCoMKgwqBmb3IgcmVjb3JkIGluIGV2ZW50WydSZWNvcmRzJ106RU5EIFJlcXVlc3RJZDogM2M3YTBhNmEtYmM4YS00MWUyLWI5NzItMmJkNGM1ZmE0ZmUxClJFUE9SVCBSZXF1ZXN0SWQ6IDNjN2EwYTZhLWJjOGEtNDFlMi1iOTcyLTJiZDRjNWZhNGZlMQlEdXJhdGlvbjogNC4xMyBtcwlCaWxsZWQgRHVyYXRpb246IDUgbXMJTWVtb3J5IFNpemU6IDEyOCBNQglNYXggTWVtb3J5IFVzZWQ6IDMxIE1CCUluaXQgRHVyYXRpb246IDc0LjUwIG1zCQo=', 'x-amzn-trace-id': 'Root=1-67387e26-69be6870135a1afe3433f53e;Parent=75fc686d750fd7fc;Sampled=0;Lineage=1:1efcaaf0:0'}, 'RetryAttempts': 0}, 'Payload': '{"errorMessage": "\'Records\'", "errorType": "KeyError", "requestId": "3c7a0a6a-bc8a-41e2-b972-2bd4c5fa4fe1", "stackTrace": ["  File \\"/var/task/lambda_function.py\\", line 7, in lambda_handler\\n    for record in event[\'Records\']:\\n"]}'})
[2024-11-16T11:12:38.973+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=model_training_pipeline, task_id=invoke_lambda_function, execution_date=20241116T111231, start_date=20241116T111237, end_date=20241116T111238
[2024-11-16T11:12:38.985+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 242 for task invoke_lambda_function (('Lambda function execution resulted in error', {'ResponseMetadata': {'RequestId': '3c7a0a6a-bc8a-41e2-b972-2bd4c5fa4fe1', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Sat, 16 Nov 2024 11:12:38 GMT', 'content-type': 'application/json', 'content-length': '232', 'connection': 'keep-alive', 'x-amzn-requestid': '3c7a0a6a-bc8a-41e2-b972-2bd4c5fa4fe1', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amz-log-result': 'U1RBUlQgUmVxdWVzdElkOiAzYzdhMGE2YS1iYzhhLTQxZTItYjk3Mi0yYmQ0YzVmYTRmZTEgVmVyc2lvbjogJExBVEVTVApMQU1CREFfV0FSTklORzogVW5oYW5kbGVkIGV4Y2VwdGlvbi4gVGhlIG1vc3QgbGlrZWx5IGNhdXNlIGlzIGFuIGlzc3VlIGluIHRoZSBmdW5jdGlvbiBjb2RlLiBIb3dldmVyLCBpbiByYXJlIGNhc2VzLCBhIExhbWJkYSBydW50aW1lIHVwZGF0ZSBjYW4gY2F1c2UgdW5leHBlY3RlZCBmdW5jdGlvbiBiZWhhdmlvci4gRm9yIGZ1bmN0aW9ucyB1c2luZyBtYW5hZ2VkIHJ1bnRpbWVzLCBydW50aW1lIHVwZGF0ZXMgY2FuIGJlIHRyaWdnZXJlZCBieSBhIGZ1bmN0aW9uIGNoYW5nZSwgb3IgY2FuIGJlIGFwcGxpZWQgYXV0b21hdGljYWxseS4gVG8gZGV0ZXJtaW5lIGlmIHRoZSBydW50aW1lIGhhcyBiZWVuIHVwZGF0ZWQsIGNoZWNrIHRoZSBydW50aW1lIHZlcnNpb24gaW4gdGhlIElOSVRfU1RBUlQgbG9nIGVudHJ5LiBJZiB0aGlzIGVycm9yIGNvcnJlbGF0ZXMgd2l0aCBhIGNoYW5nZSBpbiB0aGUgcnVudGltZSB2ZXJzaW9uLCB5b3UgbWF5IGJlIGFibGUgdG8gbWl0aWdhdGUgdGhpcyBlcnJvciBieSB0ZW1wb3JhcmlseSByb2xsaW5nIGJhY2sgdG8gdGhlIHByZXZpb3VzIHJ1bnRpbWUgdmVyc2lvbi4gRm9yIG1vcmUgaW5mb3JtYXRpb24sIHNlZSBodHRwczovL2RvY3MuYXdzLmFtYXpvbi5jb20vbGFtYmRhL2xhdGVzdC9kZy9ydW50aW1lcy11cGRhdGUuaHRtbA1bRVJST1JdIEtleUVycm9yOiAnUmVjb3JkcycKVHJhY2ViYWNrIChtb3N0IHJlY2VudCBjYWxsIGxhc3QpOgrCoMKgRmlsZSAiL3Zhci90YXNrL2xhbWJkYV9mdW5jdGlvbi5weSIsIGxpbmUgNywgaW4gbGFtYmRhX2hhbmRsZXIKwqDCoMKgwqBmb3IgcmVjb3JkIGluIGV2ZW50WydSZWNvcmRzJ106RU5EIFJlcXVlc3RJZDogM2M3YTBhNmEtYmM4YS00MWUyLWI5NzItMmJkNGM1ZmE0ZmUxClJFUE9SVCBSZXF1ZXN0SWQ6IDNjN2EwYTZhLWJjOGEtNDFlMi1iOTcyLTJiZDRjNWZhNGZlMQlEdXJhdGlvbjogNC4xMyBtcwlCaWxsZWQgRHVyYXRpb246IDUgbXMJTWVtb3J5IFNpemU6IDEyOCBNQglNYXggTWVtb3J5IFVzZWQ6IDMxIE1CCUluaXQgRHVyYXRpb246IDc0LjUwIG1zCQo=', 'x-amzn-trace-id': 'Root=1-67387e26-69be6870135a1afe3433f53e;Parent=75fc686d750fd7fc;Sampled=0;Lineage=1:1efcaaf0:0'}, 'RetryAttempts': 0}, 'Payload': '{"errorMessage": "\'Records\'", "errorType": "KeyError", "requestId": "3c7a0a6a-bc8a-41e2-b972-2bd4c5fa4fe1", "stackTrace": ["  File \\"/var/task/lambda_function.py\\", line 7, in lambda_handler\\n    for record in event[\'Records\']:\\n"]}'}); 79086)
[2024-11-16T11:12:39.010+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-16T11:12:39.038+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
