[2024-11-04T13:22:16.472+0000] {processor.py:157} INFO - Started process (PID=171) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:22:16.473+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:22:16.475+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:22:16.474+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:22:18.299+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:22:18.257+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:22:18.309+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:22:18.346+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.879 seconds
[2024-11-04T13:22:48.606+0000] {processor.py:157} INFO - Started process (PID=177) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:22:48.607+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:22:48.608+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:22:48.607+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:22:49.058+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:22:49.050+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:22:49.060+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:22:49.078+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.475 seconds
[2024-11-04T13:23:19.368+0000] {processor.py:157} INFO - Started process (PID=183) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:23:19.369+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:23:19.371+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:23:19.370+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:23:20.466+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:23:20.417+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:23:20.477+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:23:20.504+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.141 seconds
[2024-11-04T13:23:28.440+0000] {processor.py:157} INFO - Started process (PID=189) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:23:28.441+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:23:28.442+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:23:28.442+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:23:29.188+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:23:29.177+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:23:29.191+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:23:29.212+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.775 seconds
[2024-11-04T13:23:59.405+0000] {processor.py:157} INFO - Started process (PID=195) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:23:59.406+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:23:59.407+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:23:59.407+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:23:59.949+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:23:59.938+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:23:59.952+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:23:59.970+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.567 seconds
[2024-11-04T13:24:30.217+0000] {processor.py:157} INFO - Started process (PID=201) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:24:30.218+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:24:30.219+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:24:30.218+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:24:30.662+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:24:30.653+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:24:30.664+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:24:30.689+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.475 seconds
[2024-11-04T13:25:00.884+0000] {processor.py:157} INFO - Started process (PID=207) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:25:00.885+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:25:00.886+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:25:00.886+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:25:01.279+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:25:01.272+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:25:01.281+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:25:01.298+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.416 seconds
[2024-11-04T13:25:31.530+0000] {processor.py:157} INFO - Started process (PID=213) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:25:31.531+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:25:31.532+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:25:31.532+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:25:32.013+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:25:32.003+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:25:32.015+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:25:32.033+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.505 seconds
[2024-11-04T13:26:02.228+0000] {processor.py:157} INFO - Started process (PID=219) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:26:02.229+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:26:02.229+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:26:02.229+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:26:02.649+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:26:02.640+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:26:02.667+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:26:02.685+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.460 seconds
[2024-11-04T13:26:13.853+0000] {processor.py:157} INFO - Started process (PID=225) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:26:13.855+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:26:13.857+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:26:13.856+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:26:15.045+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:26:14.991+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:26:15.056+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:26:15.086+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.237 seconds
[2024-11-04T13:26:45.322+0000] {processor.py:157} INFO - Started process (PID=231) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:26:45.323+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:26:45.324+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:26:45.323+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:26:45.733+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:26:45.725+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:26:45.735+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:26:45.753+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.433 seconds
[2024-11-04T13:27:16.001+0000] {processor.py:157} INFO - Started process (PID=237) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:27:16.002+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:27:16.004+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:27:16.003+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:27:16.927+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:27:16.877+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:27:16.939+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:27:16.964+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.966 seconds
[2024-11-04T13:27:21.360+0000] {processor.py:157} INFO - Started process (PID=243) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:27:21.361+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:27:21.363+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:27:21.363+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:27:22.587+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:27:22.538+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:27:22.600+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:27:22.638+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.283 seconds
[2024-11-04T13:27:52.848+0000] {processor.py:157} INFO - Started process (PID=249) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:27:52.849+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:27:52.850+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:27:52.850+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:27:53.249+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:27:53.241+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:27:53.250+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:27:53.266+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.420 seconds
[2024-11-04T13:28:23.536+0000] {processor.py:157} INFO - Started process (PID=255) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:28:23.537+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:28:23.539+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:28:23.538+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:28:24.476+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:28:24.438+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:28:24.484+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:28:24.507+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.975 seconds
[2024-11-04T13:28:54.694+0000] {processor.py:157} INFO - Started process (PID=261) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:28:54.695+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:28:54.696+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:28:54.695+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:28:55.108+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:28:55.100+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:28:55.109+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:28:55.126+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.434 seconds
[2024-11-04T13:29:25.330+0000] {processor.py:157} INFO - Started process (PID=267) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:29:25.331+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:29:25.331+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:29:25.331+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:29:25.712+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:29:25.704+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:29:25.713+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:29:25.730+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.403 seconds
[2024-11-04T13:29:55.994+0000] {processor.py:157} INFO - Started process (PID=273) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:29:55.995+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:29:55.996+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:29:55.996+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:29:56.852+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:29:56.813+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:29:56.863+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:29:56.892+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.901 seconds
[2024-11-04T13:30:16.043+0000] {processor.py:157} INFO - Started process (PID=279) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:30:16.044+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:30:16.045+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:30:16.044+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:30:16.569+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:30:16.558+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:30:16.572+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:30:16.591+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.552 seconds
[2024-11-04T13:30:18.058+0000] {processor.py:157} INFO - Started process (PID=285) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:30:18.059+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:30:18.060+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:30:18.060+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:30:18.506+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:30:18.497+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:30:18.507+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:30:18.526+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.470 seconds
[2024-11-04T13:30:48.712+0000] {processor.py:157} INFO - Started process (PID=291) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:30:48.713+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:30:48.714+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:30:48.714+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:30:49.107+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:30:49.098+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:30:49.108+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:30:49.134+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.424 seconds
[2024-11-04T13:31:19.390+0000] {processor.py:157} INFO - Started process (PID=297) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:31:19.391+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:31:19.393+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:31:19.392+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:31:20.274+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:31:20.236+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:31:20.282+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:31:20.312+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.926 seconds
[2024-11-04T13:31:50.573+0000] {processor.py:157} INFO - Started process (PID=303) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:31:50.575+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:31:50.576+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:31:50.576+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:31:51.465+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:31:51.420+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:31:51.477+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:31:51.502+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.932 seconds
[2024-11-04T13:32:22.216+0000] {processor.py:157} INFO - Started process (PID=309) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:32:22.217+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:32:22.219+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:32:22.218+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:32:22.959+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:32:22.946+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:32:22.962+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:32:23.003+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.790 seconds
[2024-11-04T13:32:43.514+0000] {processor.py:157} INFO - Started process (PID=315) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:32:43.516+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:32:43.518+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:32:43.517+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:32:43.580+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:32:43.578+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 19
    with DAG(dag_id='noaa_etl_pipeline', default_args=default_args, schedule_interval = timedelta(7), )
                                                                                                      ^
SyntaxError: invalid syntax
[2024-11-04T13:32:43.581+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:32:43.605+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.094 seconds
[2024-11-04T13:33:13.696+0000] {processor.py:157} INFO - Started process (PID=320) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:33:13.697+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:33:13.697+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:33:13.697+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:33:13.711+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:33:13.710+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 19
    with DAG(dag_id='noaa_etl_pipeline', default_args=default_args, schedule_interval = timedelta(7), )
                                                                                                      ^
SyntaxError: invalid syntax
[2024-11-04T13:33:13.712+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:33:13.730+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.037 seconds
[2024-11-04T13:33:43.866+0000] {processor.py:157} INFO - Started process (PID=325) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:33:43.867+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:33:43.868+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:33:43.868+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:33:43.896+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:33:43.895+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 19
    with DAG(dag_id='noaa_etl_pipeline', default_args=default_args, schedule_interval = timedelta(7), )
                                                                                                      ^
SyntaxError: invalid syntax
[2024-11-04T13:33:43.897+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:33:43.914+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.050 seconds
[2024-11-04T13:34:14.162+0000] {processor.py:157} INFO - Started process (PID=330) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:34:14.162+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:34:14.163+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:34:14.163+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:34:14.177+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:34:14.176+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 19
    with DAG(dag_id='noaa_etl_pipeline', default_args=default_args, schedule_interval = timedelta(7), )
                                                                                                      ^
SyntaxError: invalid syntax
[2024-11-04T13:34:14.178+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:34:14.199+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.039 seconds
[2024-11-04T13:34:16.191+0000] {processor.py:157} INFO - Started process (PID=335) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:34:16.192+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:34:16.193+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:34:16.193+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:34:16.208+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:34:16.207+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 26
    
    ^
SyntaxError: unexpected EOF while parsing
[2024-11-04T13:34:16.209+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:34:16.237+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.049 seconds
[2024-11-04T13:34:46.516+0000] {processor.py:157} INFO - Started process (PID=340) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:34:46.519+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:34:46.521+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:34:46.521+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:34:46.605+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:34:46.603+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 26
    
    ^
SyntaxError: unexpected EOF while parsing
[2024-11-04T13:34:46.606+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:34:46.631+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.118 seconds
[2024-11-04T13:35:16.683+0000] {processor.py:157} INFO - Started process (PID=345) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:35:16.684+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:35:16.685+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:35:16.685+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:35:16.695+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:35:16.694+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 26
    
    ^
SyntaxError: unexpected EOF while parsing
[2024-11-04T13:35:16.696+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:35:16.721+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.040 seconds
[2024-11-04T13:35:46.917+0000] {processor.py:157} INFO - Started process (PID=350) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:35:46.918+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:35:46.920+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:35:46.920+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:35:46.990+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:35:46.989+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 26
    
    ^
SyntaxError: unexpected EOF while parsing
[2024-11-04T13:35:46.992+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:35:47.020+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.106 seconds
[2024-11-04T13:36:17.112+0000] {processor.py:157} INFO - Started process (PID=355) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:36:17.113+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:36:17.113+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:36:17.113+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:36:17.123+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:36:17.122+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 26
    
    ^
SyntaxError: unexpected EOF while parsing
[2024-11-04T13:36:17.123+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:36:17.143+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.034 seconds
[2024-11-04T13:36:47.338+0000] {processor.py:157} INFO - Started process (PID=360) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:36:47.339+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:36:47.341+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:36:47.340+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:36:47.396+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:36:47.395+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 26
    
    ^
SyntaxError: unexpected EOF while parsing
[2024-11-04T13:36:47.397+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:36:47.427+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.092 seconds
[2024-11-04T13:37:17.795+0000] {processor.py:157} INFO - Started process (PID=365) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:37:17.796+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:37:17.797+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:37:17.797+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:37:17.808+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:37:17.808+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 26
    
    ^
SyntaxError: unexpected EOF while parsing
[2024-11-04T13:37:17.809+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:37:17.827+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.034 seconds
[2024-11-04T13:37:20.875+0000] {processor.py:157} INFO - Started process (PID=370) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:37:20.877+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:37:20.878+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:37:20.878+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:37:21.951+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:37:21.909+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:37:21.961+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:37:21.986+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.113 seconds
[2024-11-04T13:37:52.128+0000] {processor.py:157} INFO - Started process (PID=376) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:37:52.129+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:37:52.130+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:37:52.130+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:37:52.666+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:37:52.656+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:37:52.669+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:37:52.686+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.561 seconds
[2024-11-04T13:38:22.935+0000] {processor.py:157} INFO - Started process (PID=382) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:38:22.936+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:38:22.938+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:38:22.937+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:38:23.839+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:38:23.797+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:38:23.848+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:38:23.878+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.946 seconds
[2024-11-04T13:38:54.091+0000] {processor.py:157} INFO - Started process (PID=388) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:38:54.092+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:38:54.093+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:38:54.092+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:38:54.496+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:38:54.488+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:38:54.498+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:38:54.515+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.426 seconds
[2024-11-04T13:39:24.781+0000] {processor.py:157} INFO - Started process (PID=394) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:39:24.783+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:39:24.784+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:39:24.784+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:39:25.642+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:39:25.605+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:39:25.651+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:39:25.671+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.894 seconds
[2024-11-04T13:39:55.877+0000] {processor.py:157} INFO - Started process (PID=400) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:39:55.878+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:39:55.878+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:39:55.878+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:39:56.353+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:39:56.344+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:39:56.355+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:39:56.375+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.501 seconds
[2024-11-04T13:40:26.651+0000] {processor.py:157} INFO - Started process (PID=406) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:40:26.652+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:40:26.654+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:40:26.654+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:40:27.534+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:40:27.496+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:40:27.543+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:40:27.566+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.920 seconds
[2024-11-04T13:40:57.778+0000] {processor.py:157} INFO - Started process (PID=412) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:40:57.779+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:40:57.780+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:40:57.780+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:40:58.193+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:40:58.185+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:40:58.195+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:40:58.213+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.437 seconds
[2024-11-04T13:41:28.483+0000] {processor.py:157} INFO - Started process (PID=418) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:41:28.485+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:41:28.486+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:41:28.486+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:41:29.387+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:41:29.349+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:41:29.397+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:41:29.417+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.937 seconds
[2024-11-04T13:41:59.634+0000] {processor.py:157} INFO - Started process (PID=424) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:41:59.635+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:41:59.636+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:41:59.636+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:42:00.133+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:42:00.125+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:42:00.135+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:42:00.152+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.521 seconds
[2024-11-04T13:42:30.326+0000] {processor.py:157} INFO - Started process (PID=430) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:42:30.328+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:42:30.330+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:42:30.329+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:42:31.280+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:42:31.237+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:42:31.291+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:42:31.314+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.991 seconds
[2024-11-04T13:43:01.496+0000] {processor.py:157} INFO - Started process (PID=436) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:43:01.497+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:43:01.498+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:43:01.497+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:43:01.903+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:43:01.894+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:43:01.904+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:43:01.930+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.436 seconds
[2024-11-04T13:43:32.196+0000] {processor.py:157} INFO - Started process (PID=442) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:43:32.197+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:43:32.199+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:43:32.199+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:43:33.056+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:43:33.027+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:43:33.063+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:43:33.092+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.899 seconds
[2024-11-04T13:44:03.290+0000] {processor.py:157} INFO - Started process (PID=448) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:44:03.291+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:44:03.292+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:44:03.292+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:44:03.683+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:44:03.675+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:44:03.685+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:44:03.708+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.420 seconds
[2024-11-04T13:44:33.966+0000] {processor.py:157} INFO - Started process (PID=454) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:44:33.967+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:44:33.969+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:44:33.968+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:44:34.712+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:44:34.683+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:44:34.720+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:44:34.741+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.778 seconds
[2024-11-04T13:45:04.922+0000] {processor.py:157} INFO - Started process (PID=460) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:45:04.923+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:45:04.924+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:45:04.924+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:45:05.332+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:45:05.324+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:45:05.334+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:45:05.358+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.438 seconds
[2024-11-04T13:45:35.609+0000] {processor.py:157} INFO - Started process (PID=466) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:45:35.610+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:45:35.612+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:45:35.611+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:45:36.250+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:45:36.232+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:45:36.253+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:45:36.273+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.666 seconds
[2024-11-04T13:46:06.440+0000] {processor.py:157} INFO - Started process (PID=472) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:46:06.441+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:46:06.441+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:46:06.441+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:46:06.841+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:46:06.834+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:46:06.843+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:46:06.868+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.430 seconds
[2024-11-04T13:46:37.127+0000] {processor.py:157} INFO - Started process (PID=478) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:46:37.128+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:46:37.129+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:46:37.129+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:46:37.897+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:46:37.877+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:46:37.901+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:46:37.929+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.805 seconds
[2024-11-04T13:47:02.794+0000] {processor.py:157} INFO - Started process (PID=484) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:47:02.795+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:47:02.796+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:47:02.796+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:47:03.242+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:47:03.234+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:47:03.244+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:47:03.260+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.469 seconds
[2024-11-04T13:47:33.578+0000] {processor.py:157} INFO - Started process (PID=490) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:47:33.579+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:47:33.581+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:47:33.580+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:47:34.481+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:47:34.442+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:47:34.491+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:47:34.515+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.940 seconds
[2024-11-04T13:48:04.736+0000] {processor.py:157} INFO - Started process (PID=496) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:48:04.737+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:48:04.738+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:48:04.737+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:48:05.153+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:48:05.145+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:48:05.155+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:48:05.172+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.438 seconds
[2024-11-04T13:48:35.506+0000] {processor.py:157} INFO - Started process (PID=502) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:48:35.508+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:48:35.511+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:48:35.510+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:48:36.750+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:48:36.703+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:48:36.761+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:48:36.795+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.294 seconds
[2024-11-04T13:48:37.903+0000] {processor.py:157} INFO - Started process (PID=508) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:48:37.904+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:48:37.906+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:48:37.905+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:48:39.118+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:48:39.051+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:48:39.133+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:48:39.176+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.277 seconds
[2024-11-04T13:48:56.005+0000] {processor.py:157} INFO - Started process (PID=514) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:48:56.006+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:48:56.007+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:48:56.007+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:48:56.543+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:48:56.534+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:48:56.545+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:48:56.564+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.562 seconds
[2024-11-04T13:49:26.806+0000] {processor.py:157} INFO - Started process (PID=520) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:49:26.807+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:49:26.808+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:49:26.808+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:49:27.688+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:49:27.647+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:49:27.698+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:49:27.718+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.915 seconds
[2024-11-04T13:49:57.926+0000] {processor.py:157} INFO - Started process (PID=526) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:49:57.927+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:49:57.928+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:49:57.927+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:49:58.329+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:49:58.321+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:49:58.330+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:49:58.348+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.424 seconds
[2024-11-04T13:50:28.635+0000] {processor.py:157} INFO - Started process (PID=532) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:50:28.637+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:50:28.638+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:50:28.638+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:50:29.701+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:50:29.658+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:50:29.710+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:50:29.734+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.103 seconds
[2024-11-04T13:50:42.785+0000] {processor.py:157} INFO - Started process (PID=538) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:50:42.786+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:50:42.788+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:50:42.788+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:50:43.728+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:50:43.704+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:50:43.734+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:50:43.763+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.982 seconds
[2024-11-04T13:51:02.885+0000] {processor.py:157} INFO - Started process (PID=544) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:51:02.886+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:51:02.887+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:51:02.886+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:51:03.335+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:51:03.328+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:51:03.337+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:51:03.354+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.471 seconds
[2024-11-04T13:51:33.647+0000] {processor.py:157} INFO - Started process (PID=550) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:51:33.649+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:51:33.650+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:51:33.650+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:51:34.728+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:51:34.686+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:51:34.739+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:51:34.765+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.121 seconds
[2024-11-04T13:52:04.827+0000] {processor.py:157} INFO - Started process (PID=556) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:52:04.828+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:52:04.829+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:52:04.829+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:52:05.293+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:52:05.280+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:52:05.295+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:52:05.322+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.497 seconds
[2024-11-04T13:52:29.978+0000] {processor.py:157} INFO - Started process (PID=562) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:52:29.980+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:52:29.982+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:52:29.981+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:52:31.011+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:52:30.968+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:52:31.021+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:52:31.053+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.079 seconds
[2024-11-04T13:52:42.220+0000] {processor.py:157} INFO - Started process (PID=568) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:52:42.222+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:52:42.223+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:52:42.223+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:52:42.256+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:52:42.255+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 46
    noaa_extraction >> modify_date_format >> impute_missing_values >> calculate_missing_average_temperature \
    pivot_data >> drop_columns
    ^
SyntaxError: invalid syntax
[2024-11-04T13:52:42.257+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:52:42.282+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.066 seconds
[2024-11-04T13:52:54.282+0000] {processor.py:157} INFO - Started process (PID=573) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:52:54.283+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:52:54.284+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:52:54.284+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:52:54.865+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:52:54.855+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:52:54.867+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:52:54.885+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.607 seconds
[2024-11-04T13:53:21.053+0000] {processor.py:157} INFO - Started process (PID=579) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:53:21.054+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:53:21.055+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:53:21.054+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:53:21.523+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:53:21.515+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:53:21.525+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:53:21.549+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.498 seconds
[2024-11-04T13:53:39.711+0000] {processor.py:157} INFO - Started process (PID=585) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:53:39.713+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:53:39.715+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:53:39.714+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:53:40.629+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:53:40.598+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:53:40.636+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:53:40.666+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.958 seconds
[2024-11-04T13:53:48.794+0000] {processor.py:157} INFO - Started process (PID=591) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:53:48.795+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:53:48.796+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:53:48.796+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:53:49.336+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:53:49.327+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:53:49.338+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:53:49.365+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.573 seconds
[2024-11-04T13:53:55.841+0000] {processor.py:157} INFO - Started process (PID=597) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:53:55.842+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:53:55.843+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:53:55.842+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:53:56.357+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:53:56.347+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:53:56.359+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:53:56.379+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.541 seconds
[2024-11-04T13:54:26.717+0000] {processor.py:157} INFO - Started process (PID=603) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:54:26.720+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:54:26.722+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:54:26.722+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:54:27.998+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:54:27.932+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:54:28.013+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:54:28.036+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.322 seconds
[2024-11-04T13:54:58.313+0000] {processor.py:157} INFO - Started process (PID=609) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:54:58.314+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:54:58.315+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:54:58.314+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:54:58.818+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:54:58.807+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:54:58.820+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:54:58.846+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.536 seconds
[2024-11-04T13:55:29.103+0000] {processor.py:157} INFO - Started process (PID=615) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:55:29.105+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:55:29.106+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:55:29.106+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:55:30.071+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:55:30.028+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:55:30.081+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:55:30.106+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.006 seconds
[2024-11-04T13:56:00.393+0000] {processor.py:157} INFO - Started process (PID=621) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:56:00.394+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-04T13:56:00.395+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:56:00.395+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:56:01.312+0000] {logging_mixin.py:151} INFO - [2024-11-04T13:56:01.272+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-04T13:56:01.320+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-04T13:56:01.342+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.953 seconds
