[2024-11-16T12:45:21.601+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-16T12:45:17.454307+00:00/task_id=invoke_lambda_function permission to 509
[2024-11-16T12:45:21.601+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-16T12:45:17.454307+00:00/task_id=invoke_lambda_function permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-16T12:45:17.454307+00:00/task_id=invoke_lambda_function'
[2024-11-16T12:45:21.623+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-16T12:45:17.454307+00:00/task_id=invoke_lambda_function permission to 509
[2024-11-16T12:45:21.624+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-16T12:45:17.454307+00:00/task_id=invoke_lambda_function permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-16T12:45:17.454307+00:00/task_id=invoke_lambda_function'
[2024-11-16T12:45:21.646+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_training_pipeline.invoke_lambda_function manual__2024-11-16T12:45:17.454307+00:00 [queued]>
[2024-11-16T12:45:21.653+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_training_pipeline.invoke_lambda_function manual__2024-11-16T12:45:17.454307+00:00 [queued]>
[2024-11-16T12:45:21.654+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-11-16T12:45:21.665+0000] {taskinstance.py:1382} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_function> on 2024-11-16 12:45:17.454307+00:00
[2024-11-16T12:45:21.673+0000] {standard_task_runner.py:57} INFO - Started process 94142 to run task
[2024-11-16T12:45:21.675+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'model_training_pipeline', 'invoke_lambda_function', 'manual__2024-11-16T12:45:17.454307+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/model_training_pipeline_dag/model_training_dag.py', '--cfg-path', '/tmp/tmpgmo9qdgz']
[2024-11-16T12:45:21.677+0000] {standard_task_runner.py:85} INFO - Job 250: Subtask invoke_lambda_function
[2024-11-16T12:45:21.714+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-16T12:45:17.454307+00:00/task_id=invoke_lambda_function permission to 509
[2024-11-16T12:45:21.715+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-16T12:45:17.454307+00:00/task_id=invoke_lambda_function permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=model_training_pipeline/run_id=manual__2024-11-16T12:45:17.454307+00:00/task_id=invoke_lambda_function'
[2024-11-16T12:45:21.716+0000] {task_command.py:415} INFO - Running <TaskInstance: model_training_pipeline.invoke_lambda_function manual__2024-11-16T12:45:17.454307+00:00 [running]> on host 16801ac1f6e4
[2024-11-16T12:45:21.780+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_training_pipeline' AIRFLOW_CTX_TASK_ID='invoke_lambda_function' AIRFLOW_CTX_EXECUTION_DATE='2024-11-16T12:45:17.454307+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-16T12:45:17.454307+00:00'
[2024-11-16T12:45:21.781+0000] {lambda_function.py:177} INFO - Invoking AWS Lambda function: natural_gas_spot_prices_transformation_trigger with payload: None
[2024-11-16T12:45:21.789+0000] {base.py:73} INFO - Using connection ID 'aws_connection' for task execution.
[2024-11-16T12:45:21.790+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_connection', conn_type='aws') credentials retrieved from login and password.
[2024-11-16T12:45:22.947+0000] {lambda_function.py:186} INFO - Lambda response metadata: {'RequestId': 'bfa2f0d7-e118-4f35-9b54-cb7375867d89', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Sat, 16 Nov 2024 12:45:22 GMT', 'content-type': 'application/json', 'content-length': '232', 'connection': 'keep-alive', 'x-amzn-requestid': 'bfa2f0d7-e118-4f35-9b54-cb7375867d89', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amz-log-result': 'U1RBUlQgUmVxdWVzdElkOiBiZmEyZjBkNy1lMTE4LTRmMzUtOWI1NC1jYjczNzU4NjdkODkgVmVyc2lvbjogJExBVEVTVAp0aGlzIGlzIHRoZSB7fQpMQU1CREFfV0FSTklORzogVW5oYW5kbGVkIGV4Y2VwdGlvbi4gVGhlIG1vc3QgbGlrZWx5IGNhdXNlIGlzIGFuIGlzc3VlIGluIHRoZSBmdW5jdGlvbiBjb2RlLiBIb3dldmVyLCBpbiByYXJlIGNhc2VzLCBhIExhbWJkYSBydW50aW1lIHVwZGF0ZSBjYW4gY2F1c2UgdW5leHBlY3RlZCBmdW5jdGlvbiBiZWhhdmlvci4gRm9yIGZ1bmN0aW9ucyB1c2luZyBtYW5hZ2VkIHJ1bnRpbWVzLCBydW50aW1lIHVwZGF0ZXMgY2FuIGJlIHRyaWdnZXJlZCBieSBhIGZ1bmN0aW9uIGNoYW5nZSwgb3IgY2FuIGJlIGFwcGxpZWQgYXV0b21hdGljYWxseS4gVG8gZGV0ZXJtaW5lIGlmIHRoZSBydW50aW1lIGhhcyBiZWVuIHVwZGF0ZWQsIGNoZWNrIHRoZSBydW50aW1lIHZlcnNpb24gaW4gdGhlIElOSVRfU1RBUlQgbG9nIGVudHJ5LiBJZiB0aGlzIGVycm9yIGNvcnJlbGF0ZXMgd2l0aCBhIGNoYW5nZSBpbiB0aGUgcnVudGltZSB2ZXJzaW9uLCB5b3UgbWF5IGJlIGFibGUgdG8gbWl0aWdhdGUgdGhpcyBlcnJvciBieSB0ZW1wb3JhcmlseSByb2xsaW5nIGJhY2sgdG8gdGhlIHByZXZpb3VzIHJ1bnRpbWUgdmVyc2lvbi4gRm9yIG1vcmUgaW5mb3JtYXRpb24sIHNlZSBodHRwczovL2RvY3MuYXdzLmFtYXpvbi5jb20vbGFtYmRhL2xhdGVzdC9kZy9ydW50aW1lcy11cGRhdGUuaHRtbA1bRVJST1JdIEtleUVycm9yOiAnUmVjb3JkcycKVHJhY2ViYWNrIChtb3N0IHJlY2VudCBjYWxsIGxhc3QpOgrCoMKgRmlsZSAiL3Zhci90YXNrL2xhbWJkYV9mdW5jdGlvbi5weSIsIGxpbmUgOCwgaW4gbGFtYmRhX2hhbmRsZXIKwqDCoMKgwqBmb3IgcmVjb3JkIGluIGV2ZW50WydSZWNvcmRzJ106RU5EIFJlcXVlc3RJZDogYmZhMmYwZDctZTExOC00ZjM1LTliNTQtY2I3Mzc1ODY3ZDg5ClJFUE9SVCBSZXF1ZXN0SWQ6IGJmYTJmMGQ3LWUxMTgtNGYzNS05YjU0LWNiNzM3NTg2N2Q4OQlEdXJhdGlvbjogMjguNDYgbXMJQmlsbGVkIER1cmF0aW9uOiAyOSBtcwlNZW1vcnkgU2l6ZTogMTI4IE1CCU1heCBNZW1vcnkgVXNlZDogMzIgTUIJSW5pdCBEdXJhdGlvbjogNzUuNTYgbXMJCg==', 'x-amzn-trace-id': 'Root=1-673893e2-7bafa52309c0c94c39c1c02d;Parent=7f0ba835d5fc35ed;Sampled=0;Lineage=1:1efcaaf0:0'}, 'RetryAttempts': 0}
[2024-11-16T12:45:22.948+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/operators/lambda_function.py", line 192, in execute
    raise ValueError(
ValueError: ('Lambda function execution resulted in error', {'ResponseMetadata': {'RequestId': 'bfa2f0d7-e118-4f35-9b54-cb7375867d89', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Sat, 16 Nov 2024 12:45:22 GMT', 'content-type': 'application/json', 'content-length': '232', 'connection': 'keep-alive', 'x-amzn-requestid': 'bfa2f0d7-e118-4f35-9b54-cb7375867d89', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amz-log-result': 'U1RBUlQgUmVxdWVzdElkOiBiZmEyZjBkNy1lMTE4LTRmMzUtOWI1NC1jYjczNzU4NjdkODkgVmVyc2lvbjogJExBVEVTVAp0aGlzIGlzIHRoZSB7fQpMQU1CREFfV0FSTklORzogVW5oYW5kbGVkIGV4Y2VwdGlvbi4gVGhlIG1vc3QgbGlrZWx5IGNhdXNlIGlzIGFuIGlzc3VlIGluIHRoZSBmdW5jdGlvbiBjb2RlLiBIb3dldmVyLCBpbiByYXJlIGNhc2VzLCBhIExhbWJkYSBydW50aW1lIHVwZGF0ZSBjYW4gY2F1c2UgdW5leHBlY3RlZCBmdW5jdGlvbiBiZWhhdmlvci4gRm9yIGZ1bmN0aW9ucyB1c2luZyBtYW5hZ2VkIHJ1bnRpbWVzLCBydW50aW1lIHVwZGF0ZXMgY2FuIGJlIHRyaWdnZXJlZCBieSBhIGZ1bmN0aW9uIGNoYW5nZSwgb3IgY2FuIGJlIGFwcGxpZWQgYXV0b21hdGljYWxseS4gVG8gZGV0ZXJtaW5lIGlmIHRoZSBydW50aW1lIGhhcyBiZWVuIHVwZGF0ZWQsIGNoZWNrIHRoZSBydW50aW1lIHZlcnNpb24gaW4gdGhlIElOSVRfU1RBUlQgbG9nIGVudHJ5LiBJZiB0aGlzIGVycm9yIGNvcnJlbGF0ZXMgd2l0aCBhIGNoYW5nZSBpbiB0aGUgcnVudGltZSB2ZXJzaW9uLCB5b3UgbWF5IGJlIGFibGUgdG8gbWl0aWdhdGUgdGhpcyBlcnJvciBieSB0ZW1wb3JhcmlseSByb2xsaW5nIGJhY2sgdG8gdGhlIHByZXZpb3VzIHJ1bnRpbWUgdmVyc2lvbi4gRm9yIG1vcmUgaW5mb3JtYXRpb24sIHNlZSBodHRwczovL2RvY3MuYXdzLmFtYXpvbi5jb20vbGFtYmRhL2xhdGVzdC9kZy9ydW50aW1lcy11cGRhdGUuaHRtbA1bRVJST1JdIEtleUVycm9yOiAnUmVjb3JkcycKVHJhY2ViYWNrIChtb3N0IHJlY2VudCBjYWxsIGxhc3QpOgrCoMKgRmlsZSAiL3Zhci90YXNrL2xhbWJkYV9mdW5jdGlvbi5weSIsIGxpbmUgOCwgaW4gbGFtYmRhX2hhbmRsZXIKwqDCoMKgwqBmb3IgcmVjb3JkIGluIGV2ZW50WydSZWNvcmRzJ106RU5EIFJlcXVlc3RJZDogYmZhMmYwZDctZTExOC00ZjM1LTliNTQtY2I3Mzc1ODY3ZDg5ClJFUE9SVCBSZXF1ZXN0SWQ6IGJmYTJmMGQ3LWUxMTgtNGYzNS05YjU0LWNiNzM3NTg2N2Q4OQlEdXJhdGlvbjogMjguNDYgbXMJQmlsbGVkIER1cmF0aW9uOiAyOSBtcwlNZW1vcnkgU2l6ZTogMTI4IE1CCU1heCBNZW1vcnkgVXNlZDogMzIgTUIJSW5pdCBEdXJhdGlvbjogNzUuNTYgbXMJCg==', 'x-amzn-trace-id': 'Root=1-673893e2-7bafa52309c0c94c39c1c02d;Parent=7f0ba835d5fc35ed;Sampled=0;Lineage=1:1efcaaf0:0'}, 'RetryAttempts': 0}, 'Payload': '{"errorMessage": "\'Records\'", "errorType": "KeyError", "requestId": "bfa2f0d7-e118-4f35-9b54-cb7375867d89", "stackTrace": ["  File \\"/var/task/lambda_function.py\\", line 8, in lambda_handler\\n    for record in event[\'Records\']:\\n"]}'})
[2024-11-16T12:45:22.956+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=model_training_pipeline, task_id=invoke_lambda_function, execution_date=20241116T124517, start_date=20241116T124521, end_date=20241116T124522
[2024-11-16T12:45:22.969+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 250 for task invoke_lambda_function (('Lambda function execution resulted in error', {'ResponseMetadata': {'RequestId': 'bfa2f0d7-e118-4f35-9b54-cb7375867d89', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Sat, 16 Nov 2024 12:45:22 GMT', 'content-type': 'application/json', 'content-length': '232', 'connection': 'keep-alive', 'x-amzn-requestid': 'bfa2f0d7-e118-4f35-9b54-cb7375867d89', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amz-log-result': 'U1RBUlQgUmVxdWVzdElkOiBiZmEyZjBkNy1lMTE4LTRmMzUtOWI1NC1jYjczNzU4NjdkODkgVmVyc2lvbjogJExBVEVTVAp0aGlzIGlzIHRoZSB7fQpMQU1CREFfV0FSTklORzogVW5oYW5kbGVkIGV4Y2VwdGlvbi4gVGhlIG1vc3QgbGlrZWx5IGNhdXNlIGlzIGFuIGlzc3VlIGluIHRoZSBmdW5jdGlvbiBjb2RlLiBIb3dldmVyLCBpbiByYXJlIGNhc2VzLCBhIExhbWJkYSBydW50aW1lIHVwZGF0ZSBjYW4gY2F1c2UgdW5leHBlY3RlZCBmdW5jdGlvbiBiZWhhdmlvci4gRm9yIGZ1bmN0aW9ucyB1c2luZyBtYW5hZ2VkIHJ1bnRpbWVzLCBydW50aW1lIHVwZGF0ZXMgY2FuIGJlIHRyaWdnZXJlZCBieSBhIGZ1bmN0aW9uIGNoYW5nZSwgb3IgY2FuIGJlIGFwcGxpZWQgYXV0b21hdGljYWxseS4gVG8gZGV0ZXJtaW5lIGlmIHRoZSBydW50aW1lIGhhcyBiZWVuIHVwZGF0ZWQsIGNoZWNrIHRoZSBydW50aW1lIHZlcnNpb24gaW4gdGhlIElOSVRfU1RBUlQgbG9nIGVudHJ5LiBJZiB0aGlzIGVycm9yIGNvcnJlbGF0ZXMgd2l0aCBhIGNoYW5nZSBpbiB0aGUgcnVudGltZSB2ZXJzaW9uLCB5b3UgbWF5IGJlIGFibGUgdG8gbWl0aWdhdGUgdGhpcyBlcnJvciBieSB0ZW1wb3JhcmlseSByb2xsaW5nIGJhY2sgdG8gdGhlIHByZXZpb3VzIHJ1bnRpbWUgdmVyc2lvbi4gRm9yIG1vcmUgaW5mb3JtYXRpb24sIHNlZSBodHRwczovL2RvY3MuYXdzLmFtYXpvbi5jb20vbGFtYmRhL2xhdGVzdC9kZy9ydW50aW1lcy11cGRhdGUuaHRtbA1bRVJST1JdIEtleUVycm9yOiAnUmVjb3JkcycKVHJhY2ViYWNrIChtb3N0IHJlY2VudCBjYWxsIGxhc3QpOgrCoMKgRmlsZSAiL3Zhci90YXNrL2xhbWJkYV9mdW5jdGlvbi5weSIsIGxpbmUgOCwgaW4gbGFtYmRhX2hhbmRsZXIKwqDCoMKgwqBmb3IgcmVjb3JkIGluIGV2ZW50WydSZWNvcmRzJ106RU5EIFJlcXVlc3RJZDogYmZhMmYwZDctZTExOC00ZjM1LTliNTQtY2I3Mzc1ODY3ZDg5ClJFUE9SVCBSZXF1ZXN0SWQ6IGJmYTJmMGQ3LWUxMTgtNGYzNS05YjU0LWNiNzM3NTg2N2Q4OQlEdXJhdGlvbjogMjguNDYgbXMJQmlsbGVkIER1cmF0aW9uOiAyOSBtcwlNZW1vcnkgU2l6ZTogMTI4IE1CCU1heCBNZW1vcnkgVXNlZDogMzIgTUIJSW5pdCBEdXJhdGlvbjogNzUuNTYgbXMJCg==', 'x-amzn-trace-id': 'Root=1-673893e2-7bafa52309c0c94c39c1c02d;Parent=7f0ba835d5fc35ed;Sampled=0;Lineage=1:1efcaaf0:0'}, 'RetryAttempts': 0}, 'Payload': '{"errorMessage": "\'Records\'", "errorType": "KeyError", "requestId": "bfa2f0d7-e118-4f35-9b54-cb7375867d89", "stackTrace": ["  File \\"/var/task/lambda_function.py\\", line 8, in lambda_handler\\n    for record in event[\'Records\']:\\n"]}'}); 94142)
[2024-11-16T12:45:23.012+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-16T12:45:23.036+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
