[2024-11-10T03:21:04.288+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=noaa_etl_pipeline/run_id=manual__2024-11-10T03:21:02.083491+00:00/task_id=modify_date_format permission to 509
[2024-11-10T03:21:04.288+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=noaa_etl_pipeline/run_id=manual__2024-11-10T03:21:02.083491+00:00/task_id=modify_date_format permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=noaa_etl_pipeline/run_id=manual__2024-11-10T03:21:02.083491+00:00/task_id=modify_date_format'
[2024-11-10T03:21:04.312+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=noaa_etl_pipeline/run_id=manual__2024-11-10T03:21:02.083491+00:00/task_id=modify_date_format permission to 509
[2024-11-10T03:21:04.313+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=noaa_etl_pipeline/run_id=manual__2024-11-10T03:21:02.083491+00:00/task_id=modify_date_format permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=noaa_etl_pipeline/run_id=manual__2024-11-10T03:21:02.083491+00:00/task_id=modify_date_format'
[2024-11-10T03:21:04.341+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: noaa_etl_pipeline.modify_date_format manual__2024-11-10T03:21:02.083491+00:00 [queued]>
[2024-11-10T03:21:04.348+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: noaa_etl_pipeline.modify_date_format manual__2024-11-10T03:21:02.083491+00:00 [queued]>
[2024-11-10T03:21:04.349+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-11-10T03:21:04.360+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): modify_date_format> on 2024-11-10 03:21:02.083491+00:00
[2024-11-10T03:21:04.368+0000] {standard_task_runner.py:57} INFO - Started process 34076 to run task
[2024-11-10T03:21:04.370+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'noaa_etl_pipeline', 'modify_date_format', 'manual__2024-11-10T03:21:02.083491+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py', '--cfg-path', '/tmp/tmpjfse9cmt']
[2024-11-10T03:21:04.371+0000] {standard_task_runner.py:85} INFO - Job 60: Subtask modify_date_format
[2024-11-10T03:21:04.409+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=noaa_etl_pipeline/run_id=manual__2024-11-10T03:21:02.083491+00:00/task_id=modify_date_format permission to 509
[2024-11-10T03:21:04.410+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=noaa_etl_pipeline/run_id=manual__2024-11-10T03:21:02.083491+00:00/task_id=modify_date_format permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=noaa_etl_pipeline/run_id=manual__2024-11-10T03:21:02.083491+00:00/task_id=modify_date_format'
[2024-11-10T03:21:04.411+0000] {task_command.py:415} INFO - Running <TaskInstance: noaa_etl_pipeline.modify_date_format manual__2024-11-10T03:21:02.083491+00:00 [running]> on host 16801ac1f6e4
[2024-11-10T03:21:04.482+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='noaa_etl_pipeline' AIRFLOW_CTX_TASK_ID='modify_date_format' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T03:21:02.083491+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-10T03:21:02.083491+00:00'
[2024-11-10T03:21:04.483+0000] {logging_mixin.py:151} INFO - full_program/extraction/daily_weather/ daily_weather_20241110
[2024-11-10T03:23:41.243+0000] {logging_mixin.py:151} INFO - date          datetime64[ns]
datatype              object
station               object
attributes            object
value                float64
city                  object
state                 object
quarter                int32
dtype: object
[2024-11-10T03:23:52.076+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 30, in modify_date_format
    s3.put_data(data=daily_weather_df, folder='full_program/extraction/daily_weather/', object_key=f'daily_weather_{formatted_date}')
  File "/opt/airflow/dags/utils/aws.py", line 95, in put_data
    data_json = json.dumps(data)
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Timestamp is not JSON serializable
[2024-11-10T03:23:52.112+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=noaa_etl_pipeline, task_id=modify_date_format, execution_date=20241110T032102, start_date=20241110T032104, end_date=20241110T032352
[2024-11-10T03:23:52.136+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 60 for task modify_date_format (Object of type Timestamp is not JSON serializable; 34076)
[2024-11-10T03:23:52.269+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-10T03:23:52.351+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
