[2024-11-10T08:16:11.368+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=natural_gas_monthly_variables_etl_pipeline/run_id=manual__2024-11-10T08:15:12.181125+00:00/task_id=drop_columns permission to 509
[2024-11-10T08:16:11.369+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=natural_gas_monthly_variables_etl_pipeline/run_id=manual__2024-11-10T08:15:12.181125+00:00/task_id=drop_columns permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=natural_gas_monthly_variables_etl_pipeline/run_id=manual__2024-11-10T08:15:12.181125+00:00/task_id=drop_columns'
[2024-11-10T08:16:11.393+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=natural_gas_monthly_variables_etl_pipeline/run_id=manual__2024-11-10T08:15:12.181125+00:00/task_id=drop_columns permission to 509
[2024-11-10T08:16:11.393+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=natural_gas_monthly_variables_etl_pipeline/run_id=manual__2024-11-10T08:15:12.181125+00:00/task_id=drop_columns permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=natural_gas_monthly_variables_etl_pipeline/run_id=manual__2024-11-10T08:15:12.181125+00:00/task_id=drop_columns'
[2024-11-10T08:16:11.428+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: natural_gas_monthly_variables_etl_pipeline.drop_columns manual__2024-11-10T08:15:12.181125+00:00 [queued]>
[2024-11-10T08:16:11.437+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: natural_gas_monthly_variables_etl_pipeline.drop_columns manual__2024-11-10T08:15:12.181125+00:00 [queued]>
[2024-11-10T08:16:11.438+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-11-10T08:16:11.451+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): drop_columns> on 2024-11-10 08:15:12.181125+00:00
[2024-11-10T08:16:11.459+0000] {standard_task_runner.py:57} INFO - Started process 75987 to run task
[2024-11-10T08:16:11.461+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'natural_gas_monthly_variables_etl_pipeline', 'drop_columns', 'manual__2024-11-10T08:15:12.181125+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/eia_natural_gas_monthly_variables_etl_pipeline_dag/natural_gas_monthly_variables_etl_pipeline_dag.py', '--cfg-path', '/tmp/tmpl2fj4_l2']
[2024-11-10T08:16:11.466+0000] {standard_task_runner.py:85} INFO - Job 93: Subtask drop_columns
[2024-11-10T08:16:11.517+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=natural_gas_monthly_variables_etl_pipeline/run_id=manual__2024-11-10T08:15:12.181125+00:00/task_id=drop_columns permission to 509
[2024-11-10T08:16:11.517+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=natural_gas_monthly_variables_etl_pipeline/run_id=manual__2024-11-10T08:15:12.181125+00:00/task_id=drop_columns permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=natural_gas_monthly_variables_etl_pipeline/run_id=manual__2024-11-10T08:15:12.181125+00:00/task_id=drop_columns'
[2024-11-10T08:16:11.518+0000] {task_command.py:415} INFO - Running <TaskInstance: natural_gas_monthly_variables_etl_pipeline.drop_columns manual__2024-11-10T08:15:12.181125+00:00 [running]> on host 16801ac1f6e4
[2024-11-10T08:16:11.587+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='natural_gas_monthly_variables_etl_pipeline' AIRFLOW_CTX_TASK_ID='drop_columns' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T08:15:12.181125+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-10T08:15:12.181125+00:00'
[2024-11-10T08:16:12.883+0000] {logging_mixin.py:151} INFO - Error retrieving metadata: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
[2024-11-10T08:16:12.890+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/eia_natural_gas_monthly_variables_etl_pipeline_dag/drop_columns.py", line 22, in drop_columns
    natural_gas_monthly_variables_df = EtlTransforms.drop_columns(df=natural_gas_monthly_variables_df, columns=['duoarea', 'area-name', 'product', 'product-name', 'process',
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 89, in drop_columns
    df = df.drop(columns=columns, axis=1)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 5258, in drop
    return super().drop(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 4549, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 4591, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6699, in drop
    raise KeyError(f"{list(labels[mask])} not found in axis")
KeyError: "['duoarea', 'area-name', 'product', 'product-name', 'process', 'process-name', 'series', 'series-description', 'units'] not found in axis"
[2024-11-10T08:16:12.908+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=natural_gas_monthly_variables_etl_pipeline, task_id=drop_columns, execution_date=20241110T081512, start_date=20241110T081611, end_date=20241110T081612
[2024-11-10T08:16:12.919+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 93 for task drop_columns ("['duoarea', 'area-name', 'product', 'product-name', 'process', 'process-name', 'series', 'series-description', 'units'] not found in axis"; 75987)
[2024-11-10T08:16:12.959+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-10T08:16:12.982+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
