[2024-11-08T04:39:37.002+0000] {processor.py:157} INFO - Started process (PID=183) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:39:37.003+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:39:37.004+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:39:37.004+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:39:37.700+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:39:37.691+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:39:37.702+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:39:37.718+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.718 seconds
[2024-11-08T04:40:09.246+0000] {processor.py:157} INFO - Started process (PID=201) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:40:09.249+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:40:09.252+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:40:09.251+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:40:11.236+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:40:11.152+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:40:11.253+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:40:11.278+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 2.037 seconds
[2024-11-08T04:40:42.074+0000] {processor.py:157} INFO - Started process (PID=219) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:40:42.075+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:40:42.077+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:40:42.076+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:40:43.057+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:40:43.037+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:40:43.062+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:40:43.087+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.017 seconds
[2024-11-08T04:41:13.819+0000] {processor.py:157} INFO - Started process (PID=237) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:41:13.820+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:41:13.822+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:41:13.821+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:41:15.085+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:41:15.032+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:41:15.096+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:41:15.118+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.303 seconds
[2024-11-08T04:41:45.698+0000] {processor.py:157} INFO - Started process (PID=255) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:41:45.699+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:41:45.701+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:41:45.700+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:41:46.485+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:41:46.473+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:41:46.488+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:41:46.510+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.815 seconds
[2024-11-08T04:42:16.950+0000] {processor.py:157} INFO - Started process (PID=273) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:42:16.951+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:42:16.952+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:42:16.952+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:42:17.730+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:42:17.718+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:42:17.732+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:42:17.753+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.806 seconds
[2024-11-08T04:42:47.903+0000] {processor.py:157} INFO - Started process (PID=291) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:42:47.903+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:42:47.905+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:42:47.904+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:42:48.641+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:42:48.631+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:42:48.643+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:42:48.681+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.781 seconds
[2024-11-08T04:43:19.179+0000] {processor.py:157} INFO - Started process (PID=309) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:43:19.180+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:43:19.181+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:43:19.181+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:43:20.106+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:43:20.090+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:43:20.110+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:43:20.139+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.965 seconds
[2024-11-08T04:43:51.281+0000] {processor.py:157} INFO - Started process (PID=327) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:43:51.283+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:43:51.285+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:43:51.284+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:43:52.888+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:43:52.805+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:43:52.902+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:43:52.931+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.654 seconds
[2024-11-08T04:44:23.120+0000] {processor.py:157} INFO - Started process (PID=345) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:44:23.121+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:44:23.122+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:44:23.122+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:44:23.870+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:44:23.858+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:44:23.873+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:44:23.914+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.797 seconds
[2024-11-08T04:44:55.524+0000] {processor.py:157} INFO - Started process (PID=368) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:44:55.527+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:44:55.530+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:44:55.529+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:44:57.114+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:44:57.055+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:44:57.126+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:44:57.152+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.632 seconds
[2024-11-08T04:45:27.781+0000] {processor.py:157} INFO - Started process (PID=391) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:45:27.783+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:45:27.784+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:45:27.784+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:45:28.655+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:45:28.644+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:45:28.657+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:45:28.678+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.901 seconds
[2024-11-08T04:45:59.962+0000] {processor.py:157} INFO - Started process (PID=414) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:45:59.963+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:45:59.966+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:45:59.965+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:46:01.275+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:46:01.222+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:46:01.287+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:46:01.311+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.353 seconds
[2024-11-08T04:46:31.367+0000] {processor.py:157} INFO - Started process (PID=442) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:46:31.367+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:46:31.368+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:46:31.368+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:46:32.088+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:46:32.077+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:46:32.090+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:46:32.111+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.747 seconds
[2024-11-08T04:47:02.996+0000] {processor.py:157} INFO - Started process (PID=468) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:47:02.998+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:47:03.001+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:47:03.000+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:47:04.697+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:47:04.637+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:47:04.714+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:47:04.747+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.755 seconds
[2024-11-08T04:47:35.280+0000] {processor.py:157} INFO - Started process (PID=493) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:47:35.280+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:47:35.281+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:47:35.281+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:47:35.914+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:47:35.905+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:47:35.916+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:47:35.934+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.657 seconds
[2024-11-08T04:48:06.462+0000] {processor.py:157} INFO - Started process (PID=521) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:48:06.463+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:48:06.465+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:48:06.464+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:48:07.458+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:48:07.427+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:48:07.466+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:48:07.488+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.030 seconds
[2024-11-08T04:48:37.814+0000] {processor.py:157} INFO - Started process (PID=544) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:48:37.815+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:48:37.817+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:48:37.817+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:48:38.523+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:48:38.511+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:48:38.527+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:48:38.549+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.740 seconds
[2024-11-08T04:50:09.790+0000] {processor.py:157} INFO - Started process (PID=183) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:50:09.791+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:50:09.792+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:50:09.792+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:50:10.448+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:50:10.437+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:50:10.450+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:50:10.467+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.680 seconds
[2024-11-08T04:50:40.890+0000] {processor.py:157} INFO - Started process (PID=201) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:50:40.891+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:50:40.893+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:50:40.893+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:50:41.540+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:50:41.531+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:50:41.542+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:50:41.560+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.672 seconds
[2024-11-08T04:51:11.754+0000] {processor.py:157} INFO - Started process (PID=219) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:51:11.755+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:51:11.756+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:51:11.756+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:51:12.426+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:51:12.414+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:51:12.428+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:51:12.447+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.696 seconds
[2024-11-08T04:51:43.380+0000] {processor.py:157} INFO - Started process (PID=237) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:51:43.381+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:51:43.382+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:51:43.381+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:51:44.006+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:51:43.995+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:51:44.009+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:51:44.034+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.657 seconds
[2024-11-08T04:52:14.765+0000] {processor.py:157} INFO - Started process (PID=255) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:52:14.766+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:52:14.767+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:52:14.767+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:52:15.416+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:52:15.406+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:52:15.419+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:52:15.436+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.673 seconds
[2024-11-08T04:52:45.809+0000] {processor.py:157} INFO - Started process (PID=273) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:52:45.810+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:52:45.810+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:52:45.810+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:52:46.443+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:52:46.434+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:52:46.445+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:52:46.471+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.665 seconds
[2024-11-08T04:53:16.784+0000] {processor.py:157} INFO - Started process (PID=291) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:53:16.785+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:53:16.786+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:53:16.786+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:53:17.378+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:53:17.369+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:53:17.380+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:53:17.405+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.623 seconds
[2024-11-08T04:53:47.832+0000] {processor.py:157} INFO - Started process (PID=309) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:53:47.833+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:53:47.834+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:53:47.834+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:53:48.454+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:53:48.445+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:53:48.457+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:53:48.473+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.644 seconds
[2024-11-08T04:54:18.844+0000] {processor.py:157} INFO - Started process (PID=327) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:54:18.844+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:54:18.845+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:54:18.845+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:54:19.453+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:54:19.443+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:54:19.455+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:54:19.474+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.633 seconds
[2024-11-08T04:54:49.934+0000] {processor.py:157} INFO - Started process (PID=345) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:54:49.935+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:54:49.936+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:54:49.936+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:54:50.606+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:54:50.595+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:54:50.609+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:54:50.630+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.699 seconds
[2024-11-08T04:55:20.705+0000] {processor.py:157} INFO - Started process (PID=363) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:55:20.706+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:55:20.707+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:55:20.707+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:55:21.351+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:55:21.341+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:55:21.353+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:55:21.372+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.670 seconds
[2024-11-08T04:55:51.948+0000] {processor.py:157} INFO - Started process (PID=381) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:55:51.949+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:55:51.950+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:55:51.950+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:55:52.579+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:55:52.570+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:55:52.582+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:55:52.601+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.656 seconds
[2024-11-08T04:56:23.025+0000] {processor.py:157} INFO - Started process (PID=397) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:56:23.026+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:56:23.028+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:56:23.027+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:56:23.799+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:56:23.788+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:56:23.802+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:56:23.824+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.802 seconds
[2024-11-08T04:56:53.873+0000] {processor.py:157} INFO - Started process (PID=417) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:56:53.874+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:56:53.875+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:56:53.875+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:56:54.626+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:56:54.615+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:56:54.629+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:56:54.657+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.788 seconds
[2024-11-08T04:57:24.979+0000] {processor.py:157} INFO - Started process (PID=435) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:57:24.980+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:57:24.981+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:57:24.981+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:57:25.466+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:57:25.456+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:57:25.469+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:57:25.489+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.513 seconds
[2024-11-08T04:57:56.257+0000] {processor.py:157} INFO - Started process (PID=453) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:57:56.259+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:57:56.260+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:57:56.259+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:57:56.852+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:57:56.840+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:57:56.855+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:57:56.879+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.624 seconds
[2024-11-08T04:58:27.212+0000] {processor.py:157} INFO - Started process (PID=471) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:58:27.212+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:58:27.213+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:58:27.213+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:58:27.711+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:58:27.701+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:58:27.714+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:58:27.732+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.523 seconds
[2024-11-08T04:58:58.017+0000] {processor.py:157} INFO - Started process (PID=489) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:58:58.017+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:58:58.018+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:58:58.018+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:58:58.533+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:58:58.522+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:58:58.536+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:58:58.557+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.543 seconds
[2024-11-08T04:59:28.860+0000] {processor.py:157} INFO - Started process (PID=507) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:59:28.861+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:59:28.862+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:59:28.862+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:59:29.370+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:59:29.359+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T04:59:29.372+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:59:29.391+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.533 seconds
[2024-11-08T04:59:59.691+0000] {processor.py:157} INFO - Started process (PID=525) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T04:59:59.692+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T04:59:59.693+0000] {logging_mixin.py:151} INFO - [2024-11-08T04:59:59.693+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:00:00.270+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:00:00.235+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:00:00.273+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:00:00.301+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.612 seconds
[2024-11-08T05:00:30.776+0000] {processor.py:157} INFO - Started process (PID=543) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:00:30.777+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:00:30.778+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:00:30.778+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:00:31.258+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:00:31.247+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:00:31.260+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:00:31.278+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.505 seconds
[2024-11-08T05:01:01.581+0000] {processor.py:157} INFO - Started process (PID=561) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:01:01.582+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:01:01.583+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:01:01.583+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:01:02.184+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:01:02.172+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:01:02.187+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:01:02.217+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.638 seconds
[2024-11-08T05:01:32.500+0000] {processor.py:157} INFO - Started process (PID=579) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:01:32.501+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:01:32.502+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:01:32.502+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:01:32.989+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:01:32.977+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:01:32.991+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:01:33.010+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.512 seconds
[2024-11-08T05:02:03.294+0000] {processor.py:157} INFO - Started process (PID=597) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:02:03.295+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:02:03.297+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:02:03.296+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:02:03.826+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:02:03.815+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:02:03.828+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:02:03.853+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.562 seconds
[2024-11-08T05:02:34.157+0000] {processor.py:157} INFO - Started process (PID=615) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:02:34.158+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:02:34.159+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:02:34.159+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:02:34.641+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:02:34.631+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:02:34.644+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:02:34.664+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.510 seconds
[2024-11-08T05:03:05.434+0000] {processor.py:157} INFO - Started process (PID=633) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:03:05.435+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:03:05.435+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:03:05.435+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:03:06.048+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:03:06.036+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:03:06.051+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:03:06.073+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.642 seconds
[2024-11-08T05:03:36.382+0000] {processor.py:157} INFO - Started process (PID=651) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:03:36.384+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:03:36.386+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:03:36.386+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:03:36.936+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:03:36.926+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:03:36.938+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:03:36.958+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.580 seconds
[2024-11-08T05:04:07.240+0000] {processor.py:157} INFO - Started process (PID=669) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:04:07.240+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:04:07.241+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:04:07.241+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:04:07.754+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:04:07.744+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:04:07.756+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:04:07.774+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.537 seconds
[2024-11-08T05:04:38.066+0000] {processor.py:157} INFO - Started process (PID=687) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:04:38.067+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:04:38.068+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:04:38.067+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:04:38.582+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:04:38.573+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:04:38.584+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:04:38.604+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.540 seconds
[2024-11-08T05:05:08.792+0000] {processor.py:157} INFO - Started process (PID=705) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:05:08.793+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:05:08.793+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:05:08.793+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:05:09.320+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:05:09.308+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:05:09.323+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:05:09.350+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.561 seconds
[2024-11-08T05:05:40.066+0000] {processor.py:157} INFO - Started process (PID=723) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:05:40.068+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:05:40.069+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:05:40.068+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:05:40.571+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:05:40.561+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:05:40.573+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:05:40.594+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.531 seconds
[2024-11-08T05:06:10.971+0000] {processor.py:157} INFO - Started process (PID=741) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:06:10.973+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:06:10.973+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:06:10.973+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:06:11.496+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:06:11.484+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:06:11.499+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:06:11.526+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.558 seconds
[2024-11-08T05:06:41.874+0000] {processor.py:157} INFO - Started process (PID=759) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:06:41.875+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:06:41.875+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:06:41.875+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:06:42.398+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:06:42.387+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:06:42.400+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:06:42.423+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.552 seconds
[2024-11-08T05:07:12.798+0000] {processor.py:157} INFO - Started process (PID=777) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:07:12.799+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:07:12.800+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:07:12.800+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:07:13.368+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:07:13.357+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:07:13.371+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:07:13.390+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.595 seconds
[2024-11-08T05:07:43.675+0000] {processor.py:157} INFO - Started process (PID=795) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:07:43.676+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:07:43.678+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:07:43.677+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:07:44.185+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:07:44.175+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:07:44.187+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:07:44.208+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.536 seconds
[2024-11-08T05:08:15.005+0000] {processor.py:157} INFO - Started process (PID=813) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:08:15.006+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:08:15.007+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:08:15.007+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:08:15.529+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:08:15.519+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:08:15.531+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:08:15.554+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.551 seconds
[2024-11-08T05:08:46.356+0000] {processor.py:157} INFO - Started process (PID=831) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:08:46.356+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:08:46.357+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:08:46.357+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:08:46.875+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:08:46.865+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:08:46.878+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:08:46.897+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.544 seconds
[2024-11-08T05:09:17.903+0000] {processor.py:157} INFO - Started process (PID=847) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:09:17.904+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:09:17.905+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:09:17.905+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:09:18.435+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:09:18.424+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:09:18.437+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:09:18.457+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.556 seconds
[2024-11-08T05:09:48.803+0000] {processor.py:157} INFO - Started process (PID=867) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:09:48.804+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:09:48.805+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:09:48.805+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:09:49.691+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:09:49.679+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:09:49.693+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:09:49.716+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.915 seconds
[2024-11-08T05:10:20.441+0000] {processor.py:157} INFO - Started process (PID=885) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:10:20.443+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:10:20.445+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:10:20.445+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:10:21.531+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:10:21.484+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:10:21.543+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:10:21.565+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.128 seconds
[2024-11-08T05:10:51.882+0000] {processor.py:157} INFO - Started process (PID=903) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:10:51.884+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:10:51.885+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:10:51.885+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:10:52.862+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:10:52.824+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:10:52.870+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:10:52.895+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.017 seconds
[2024-11-08T05:11:23.564+0000] {processor.py:157} INFO - Started process (PID=921) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:11:23.565+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:11:23.567+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:11:23.566+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:11:24.401+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:11:24.378+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:11:24.406+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:11:24.430+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.870 seconds
[2024-11-08T05:11:54.490+0000] {processor.py:157} INFO - Started process (PID=939) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:11:54.490+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:11:54.492+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:11:54.491+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:11:55.105+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:11:55.094+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:11:55.108+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:11:55.131+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.644 seconds
[2024-11-08T05:12:25.694+0000] {processor.py:157} INFO - Started process (PID=957) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:12:25.695+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:12:25.696+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:12:25.696+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:12:26.192+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:12:26.181+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:12:26.195+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:12:26.220+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.529 seconds
[2024-11-08T05:12:56.546+0000] {processor.py:157} INFO - Started process (PID=975) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:12:56.547+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:12:56.548+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:12:56.548+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:12:57.133+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:12:57.123+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:12:57.135+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:12:57.156+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.613 seconds
[2024-11-08T05:13:27.787+0000] {processor.py:157} INFO - Started process (PID=993) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:13:27.788+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:13:27.790+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:13:27.790+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:13:28.884+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:13:28.834+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:13:28.897+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:13:28.927+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.146 seconds
[2024-11-08T05:13:59.467+0000] {processor.py:157} INFO - Started process (PID=1011) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:13:59.470+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:13:59.472+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:13:59.471+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:14:00.068+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:14:00.057+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:14:00.070+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:14:00.090+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.630 seconds
[2024-11-08T05:14:30.381+0000] {processor.py:157} INFO - Started process (PID=1029) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:14:30.382+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:14:30.384+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:14:30.383+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:14:30.919+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:14:30.910+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:14:30.922+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:14:30.949+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.571 seconds
[2024-11-08T05:15:01.685+0000] {processor.py:157} INFO - Started process (PID=1047) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:15:01.687+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:15:01.688+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:15:01.688+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:15:02.776+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:15:02.729+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:15:02.787+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:15:02.812+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.132 seconds
[2024-11-08T05:15:33.004+0000] {processor.py:157} INFO - Started process (PID=1065) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:15:33.006+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:15:33.007+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:15:33.006+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:15:33.564+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:15:33.552+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:15:33.566+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:15:33.588+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.587 seconds
[2024-11-08T05:16:04.301+0000] {processor.py:157} INFO - Started process (PID=1083) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:16:04.302+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:16:04.303+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:16:04.303+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:16:04.919+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:16:04.909+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:16:04.921+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:16:04.948+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.649 seconds
[2024-11-08T05:16:35.748+0000] {processor.py:157} INFO - Started process (PID=1101) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:16:35.749+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:16:35.750+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:16:35.750+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:16:36.257+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:16:36.248+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:16:36.260+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:16:36.278+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.532 seconds
[2024-11-08T05:17:07.133+0000] {processor.py:157} INFO - Started process (PID=1119) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:17:07.134+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:17:07.135+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:17:07.135+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:17:07.705+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:17:07.694+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:17:07.707+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:17:07.733+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.604 seconds
[2024-11-08T05:17:38.438+0000] {processor.py:157} INFO - Started process (PID=1137) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:17:38.439+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:17:38.440+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:17:38.439+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:17:38.913+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:17:38.904+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:17:38.915+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:17:38.933+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.498 seconds
[2024-11-08T05:18:10.135+0000] {processor.py:157} INFO - Started process (PID=1155) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:18:10.137+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:18:10.139+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:18:10.139+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:18:11.161+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:18:11.113+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:18:11.171+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:18:11.203+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.071 seconds
[2024-11-08T05:18:41.570+0000] {processor.py:157} INFO - Started process (PID=1173) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:18:41.571+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:18:41.571+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:18:41.571+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:18:42.065+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:18:42.055+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:18:42.067+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:18:42.086+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.520 seconds
[2024-11-08T05:19:12.414+0000] {processor.py:157} INFO - Started process (PID=1191) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:19:12.416+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:19:12.417+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:19:12.416+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:19:12.918+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:19:12.909+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:19:12.921+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:19:12.940+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.528 seconds
[2024-11-08T05:19:43.611+0000] {processor.py:157} INFO - Started process (PID=1209) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:19:43.613+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:19:43.615+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:19:43.615+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:19:44.764+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:19:44.716+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:19:44.775+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:19:44.808+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.200 seconds
[2024-11-08T05:20:15.135+0000] {processor.py:157} INFO - Started process (PID=1227) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:20:15.136+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:20:15.137+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:20:15.137+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:20:15.734+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:20:15.723+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:20:15.736+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:20:15.758+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.626 seconds
[2024-11-08T05:20:46.280+0000] {processor.py:157} INFO - Started process (PID=1245) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:20:46.281+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:20:46.283+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:20:46.282+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:20:47.105+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:20:47.089+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:20:47.108+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:20:47.135+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.860 seconds
[2024-11-08T05:25:54.035+0000] {processor.py:157} INFO - Started process (PID=184) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:25:54.036+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:25:54.038+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:25:54.038+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:25:55.068+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:25:55.039+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:25:55.076+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:25:55.101+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.070 seconds
[2024-11-08T05:26:25.410+0000] {processor.py:157} INFO - Started process (PID=202) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:26:25.411+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:26:25.412+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:26:25.411+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:26:26.128+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:26:26.118+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:26:26.130+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:26:26.149+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.742 seconds
[2024-11-08T05:26:56.484+0000] {processor.py:157} INFO - Started process (PID=220) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:26:56.485+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:26:56.486+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:26:56.486+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:26:57.169+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:26:57.160+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:26:57.171+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:26:57.189+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.708 seconds
[2024-11-08T05:27:27.258+0000] {processor.py:157} INFO - Started process (PID=235) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:27:27.260+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:27:27.262+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:27:27.261+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:27:27.904+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:27:27.891+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:27:27.907+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:27:27.937+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.683 seconds
[2024-11-08T05:27:58.865+0000] {processor.py:157} INFO - Started process (PID=253) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:27:58.866+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:27:58.868+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:27:58.867+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:28:00.100+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:28:00.057+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:28:00.111+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:28:00.140+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.279 seconds
[2024-11-08T05:28:30.304+0000] {processor.py:157} INFO - Started process (PID=274) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:28:30.305+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:28:30.306+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:28:30.306+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:28:31.011+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:28:31.000+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:28:31.013+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:28:31.031+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.729 seconds
[2024-11-08T05:29:01.309+0000] {processor.py:157} INFO - Started process (PID=292) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:29:01.310+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:29:01.311+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:29:01.310+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:29:01.940+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:29:01.930+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:29:01.942+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:29:01.969+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.663 seconds
[2024-11-08T05:29:32.806+0000] {processor.py:157} INFO - Started process (PID=308) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:29:32.807+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T05:29:32.809+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:29:32.808+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:29:33.885+0000] {logging_mixin.py:151} INFO - [2024-11-08T05:29:33.858+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 6, in <module>
    from noaa_etl_pipeline_dag.modify_date_format import modify_date_format
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/modify_date_format.py", line 4, in <module>
    from transformation.etl_transforms import EtlTransforms
  File "/opt/airflow/dags/transformation/etl_transforms.py", line 5, in <module>
    from sklearn.preprocessing import RobustScaler
ModuleNotFoundError: No module named 'sklearn'
[2024-11-08T05:29:33.892+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T05:29:33.913+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 1.110 seconds
[2024-11-08T23:49:58.113+0000] {processor.py:157} INFO - Started process (PID=227) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:49:58.115+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:49:58.116+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:49:58.116+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:49:58.170+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:49:58.159+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:49:58.173+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:49:58.202+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.094 seconds
[2024-11-08T23:50:29.668+0000] {processor.py:157} INFO - Started process (PID=291) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:50:29.671+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:50:29.674+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:50:29.673+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:50:29.764+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:50:29.747+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:50:29.768+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:50:29.801+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.137 seconds
[2024-11-08T23:51:01.591+0000] {processor.py:157} INFO - Started process (PID=355) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:51:01.592+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:51:01.593+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:51:01.592+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:51:01.641+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:51:01.631+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:51:01.644+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:51:01.668+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.081 seconds
[2024-11-08T23:51:31.914+0000] {processor.py:157} INFO - Started process (PID=413) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:51:31.914+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:51:31.915+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:51:31.915+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:51:31.966+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:51:31.956+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:51:31.969+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:51:31.992+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.081 seconds
[2024-11-08T23:52:03.437+0000] {processor.py:157} INFO - Started process (PID=480) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:52:03.438+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:52:03.439+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:52:03.438+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:52:03.480+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:52:03.472+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:52:03.482+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:52:03.504+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.070 seconds
[2024-11-08T23:52:34.915+0000] {processor.py:157} INFO - Started process (PID=544) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:52:34.916+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:52:34.917+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:52:34.917+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:52:34.960+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:52:34.951+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:52:34.962+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:52:34.986+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.073 seconds
[2024-11-08T23:53:07.556+0000] {processor.py:157} INFO - Started process (PID=614) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:53:07.557+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:53:07.559+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:53:07.558+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:53:07.615+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:53:07.603+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:53:07.618+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:53:07.647+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.094 seconds
[2024-11-08T23:53:39.178+0000] {processor.py:157} INFO - Started process (PID=678) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:53:39.179+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:53:39.181+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:53:39.181+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:53:39.260+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:53:39.248+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:53:39.264+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:53:39.295+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.122 seconds
[2024-11-08T23:54:10.545+0000] {processor.py:157} INFO - Started process (PID=742) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:54:10.546+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:54:10.547+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:54:10.547+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:54:10.610+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:54:10.593+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:54:10.613+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:54:10.638+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.096 seconds
[2024-11-08T23:54:41.744+0000] {processor.py:157} INFO - Started process (PID=806) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:54:41.745+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:54:41.746+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:54:41.746+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:54:41.802+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:54:41.792+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:54:41.805+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:54:41.834+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.092 seconds
[2024-11-08T23:55:12.358+0000] {processor.py:157} INFO - Started process (PID=870) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:55:12.358+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:55:12.359+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:55:12.359+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:55:12.414+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:55:12.406+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:55:12.416+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:55:12.438+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.083 seconds
[2024-11-08T23:55:43.644+0000] {processor.py:157} INFO - Started process (PID=934) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:55:43.645+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:55:43.647+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:55:43.646+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:55:43.729+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:55:43.703+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:55:43.731+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:55:43.754+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.115 seconds
[2024-11-08T23:56:14.647+0000] {processor.py:157} INFO - Started process (PID=998) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:56:14.648+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:56:14.649+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:56:14.649+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:56:14.695+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:56:14.687+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:56:14.697+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:56:14.717+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.072 seconds
[2024-11-08T23:56:45.628+0000] {processor.py:157} INFO - Started process (PID=1062) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:56:45.629+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:56:45.630+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:56:45.630+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:56:45.671+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:56:45.663+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:56:45.673+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:56:45.700+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.076 seconds
[2024-11-08T23:57:16.750+0000] {processor.py:157} INFO - Started process (PID=1126) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:57:16.751+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:57:16.752+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:57:16.752+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:57:16.814+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:57:16.802+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:57:16.818+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:57:16.842+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.096 seconds
[2024-11-08T23:57:48.640+0000] {processor.py:157} INFO - Started process (PID=1190) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:57:48.642+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:57:48.644+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:57:48.644+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:57:48.883+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:57:48.837+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:57:48.895+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:57:48.922+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.285 seconds
[2024-11-08T23:58:19.624+0000] {processor.py:157} INFO - Started process (PID=1254) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:58:19.624+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:58:19.625+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:58:19.625+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:58:19.672+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:58:19.663+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:58:19.674+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:58:19.696+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.076 seconds
[2024-11-08T23:58:50.600+0000] {processor.py:157} INFO - Started process (PID=1318) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:58:50.601+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:58:50.601+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:58:50.601+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:58:50.646+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:58:50.637+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:58:50.648+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:58:50.670+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.073 seconds
[2024-11-08T23:59:21.586+0000] {processor.py:157} INFO - Started process (PID=1382) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:59:21.587+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:59:21.588+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:59:21.588+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:59:21.628+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:59:21.620+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:59:21.630+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:59:21.650+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.067 seconds
[2024-11-08T23:59:52.317+0000] {processor.py:157} INFO - Started process (PID=1446) to work on /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:59:52.318+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py for tasks to queue
[2024-11-08T23:59:52.319+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:59:52.319+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:59:52.370+0000] {logging_mixin.py:151} INFO - [2024-11-08T23:59:52.359+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py", line 5, in <module>
    from noaa_etl_pipeline_dag.extraction import noaa_extraction
  File "/opt/airflow/dags/noaa_etl_pipeline_dag/extraction.py", line 3, in <module>
    from extraction.noaa_api import *
  File "/opt/airflow/dags/extraction/noaa_api.py", line 5, in <module>
    from full_program.airflow.dags.utils.aws import S3, S3Metadata
ModuleNotFoundError: No module named 'full_program'
[2024-11-08T23:59:52.372+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py
[2024-11-08T23:59:52.397+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/noaa_etl_pipeline_dag/noaa_etl_pipeline_dag.py took 0.082 seconds
